export const GEMINI_API_KEY = 'AIzaSyDg9rQChqfDjHTeJvqRSEnwAmlmC_yBtd8';
export const EXPO_PUBLIC_OPENAI_API_KEY = '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';
export default { GEMINI_API_KEY, EXPO_PUBLIC_OPENAI_API_KEY }; 